// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwoav7VJI3W75212o2MeAy3Cn5QvthmXA',
    appId: '1:923736620842:web:3601f48277d53843406853',
    messagingSenderId: '923736620842',
    projectId: 'final-test-app-rootsys12',
    authDomain: 'final-test-app-rootsys12.firebaseapp.com',
    storageBucket: 'final-test-app-rootsys12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfgeZWS8c_PMTM2lYtt7giBltviN4yXkY',
    appId: '1:923736620842:android:0a80251bd6851467406853',
    messagingSenderId: '923736620842',
    projectId: 'final-test-app-rootsys12',
    storageBucket: 'final-test-app-rootsys12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFz827KxqTbfgdNsyPspfHnedPNRLJxAQ',
    appId: '1:923736620842:ios:f19080712dbfe793406853',
    messagingSenderId: '923736620842',
    projectId: 'final-test-app-rootsys12',
    storageBucket: 'final-test-app-rootsys12.firebasestorage.app',
    iosBundleId: 'com.example.testApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFz827KxqTbfgdNsyPspfHnedPNRLJxAQ',
    appId: '1:923736620842:ios:f19080712dbfe793406853',
    messagingSenderId: '923736620842',
    projectId: 'final-test-app-rootsys12',
    storageBucket: 'final-test-app-rootsys12.firebasestorage.app',
    iosBundleId: 'com.example.testApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwoav7VJI3W75212o2MeAy3Cn5QvthmXA',
    appId: '1:923736620842:web:bca2c94a5bf4379d406853',
    messagingSenderId: '923736620842',
    projectId: 'final-test-app-rootsys12',
    authDomain: 'final-test-app-rootsys12.firebaseapp.com',
    storageBucket: 'final-test-app-rootsys12.firebasestorage.app',
  );
}
